### ISSUE TITLE
TypeError while selecting cropping areas

### ISSUE THREAD

**Issue by fnunnari** [DFKI-SignLanguage/VideoProcessingTools#8]
While testing on:

    python -m dfki_sl_videotools.edit_video_bounds_batch --dir . --f mp4 --out tmp

```
crop-area is selected, inserting this to output json
video file name: bb-dev.mp4, resolution: 1080x720, number of frame: 53 
Rendering video frames... 
Something went wrong while cap.read() ... 
crop_area {'x': 402, 'y': 133, 'width': 300, 'height': 370}, isCropAreaSet: False
crop-area is selected, inserting this to output json
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/fanu01-admin/Documents/Code/DFKI-SignLanguage/VideoProcessingTools/dfki_sl_videotools/edit_video_bounds_batch.py", line 302, in <module>
    create_output_json(args.dir, args.f, args.out, args.oname)
  File "/Users/fanu01-admin/Documents/Code/DFKI-SignLanguage/VideoProcessingTools/dfki_sl_videotools/edit_video_bounds_batch.py", line 251, in create_output_json
    json.dump(out_json, f)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
```

**Comment by Daksitha** [comment]
np.abs created Int64 object which caused the issue
